name: Build tutorials

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  worker:
    name: pytorch_tutorial_build_worker
    strategy:
      matrix:
        include:
          - { shard: 1, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" }
          - { shard: 2, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" }
    runs-on: ${{ matrix.runner }}
    env:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-bionic-cuda11.7-cudnn8-py3-gcc7"
      CUDA_VERSION: "9"
    steps:
      - name: Checkout Tutorials
        uses: actions/checkout@v3

      - name: Set Up CI Environment
        shell: bash
        run: |
          set -e

          sudo apt-get -y update
          sudo apt-get -y install expect-dev moreutils

          if [ -n "${CUDA_VERSION}" ]; then
            nvidia-smi
          fi

      - name: Pull docker image
        shell: bash
        id: docker-image
        run: |
          set -ex

          # for some reason, pip installs it in a different place than what is looked at in the py file
          sudo pip3 install requests --target=/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages
          export pyTorchDockerImageTag=$(python3 .jenkins/get_docker_tag.py)

          export DOCKER_IMAGE="${DOCKER_IMAGE}:${pyTorchDockerImageTag}"
          docker pull ${DOCKER_IMAGE} >/dev/null
          echo "docker_image=${DOCKER_IMAGE}" >> "${GITHUB_OUTPUT}"

      - name: Build
        shell: bash
        env:
          DOCKER_IMAGE: ${{ steps.docker-image.outputs.docker_image }}
        run: |
          set -ex

          if [ -n "${CUDA_VERSION}" ]; then
            export id=$(docker run --gpus all -t -d -w /var/lib/jenkins ${DOCKER_IMAGE})
          else
            export id=$(docker run -t -d -w /var/lib/jenkins ${DOCKER_IMAGE})
          fi

          echo 'rm /opt/cache/bin/*' | docker exec -u root -i "$id" bash
          docker cp /home/circleci/project/. "$id:/var/lib/jenkins/workspace"

          export COMMAND='((echo "source ./workspace/env" && echo "sudo chown -R jenkins workspace && cd workspace && ./jenkins/worker.sh") | docker exec -u jenkins -i "$id" bash) 2>&1'
          echo ${COMMAND} > ./command.sh && unbuffer bash ./command.sh | ts

      - name: Upload Python Docs Preview
        uses: seemethere/upload-artifact-s3@v5
        with:
          retention-days: 14
          s3-bucket: pytorch-tutorial-build-pull-request
          if-no-files-found: error
          path: worker_${{ matrix.shard }}
          s3-prefix: temp/${{ github.event.pull_request.number }}

  manager:
    name: pytorch_tutorial_build_manager
    needs: pytorch_tutorial_build_worker
    runs-on: [self-hosted, linux.large]
    steps:
      - name: Checkout Tutorials
        uses: actions/checkout@v3

      - name:
